/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biblioteca;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;

public class App {

    public static void main(String[] args) {
        String[] books = {"Harry Potter", "The Pragmatic Programmer"};
        Biblioteca biblioteca = new Biblioteca(System.out, new BufferedReader(new InputStreamReader(System.in)), books);
        biblioteca.sayHello();
        biblioteca.chooseMenuOption();
    }
}
